# Generated by Django 3.1.1 on 2020-10-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201015_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.BigIntegerField(unique=True, verbose_name='Id Number'),
        ),
    ]
