# Generated by Django 3.1.1 on 2020-10-16 19:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('arrears', models.CharField(blank=True, max_length=100, null=True)),
                ('is_cleared', models.BooleanField(default=False, verbose_name='Arrears Cleared')),
                ('id_number', models.BigIntegerField(verbose_name='Owner Id Number')),
            ],
            options={
                'db_table': 'parcel_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857)),
                ('plot_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('zone', models.CharField(default='Zone A', max_length=50, verbose_name='Parcel Zone')),
            ],
            options={
                'db_table': 'parcels',
                'managed': False,
            },
        ),
    ]
