# Generated by Django 3.1.1 on 2021-02-04 08:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('arrears', models.CharField(blank=True, max_length=100, null=True)),
                ('is_cleared', models.BooleanField(default=False, verbose_name='Arrears Cleared')),
                ('id_number', models.BigIntegerField(verbose_name='Owner Id Number')),
                ('phone_number', models.CharField(blank=True, max_length=13, verbose_name='Phone Number')),
            ],
            options={
                'db_table': 'parcel_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857)),
                ('plot_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('zone', models.CharField(default='Zone A', max_length=50, verbose_name='Parcel Zone')),
            ],
            options={
                'db_table': 'parcels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.BigIntegerField(blank=True, null=True)),
                ('payed_on', models.DateTimeField(verbose_name='Payed On')),
                ('is_waived', models.BooleanField(default=False, verbose_name='Waiver')),
                ('payment_mode', models.CharField(choices=[('MPESA', 'M-PESA'), ('Bank', 'Bank')], max_length=50, verbose_name='Payment Method')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('balance', models.IntegerField(default=0, verbose_name='Arrear')),
                ('transaction_id', models.CharField(max_length=50, verbose_name='Transaction Id')),
                ('id_number', models.IntegerField(verbose_name='Id Number')),
            ],
            options={
                'verbose_name': 'Tax History',
                'verbose_name_plural': 'Tax History',
            },
        ),
    ]
