# Generated by Django 3.1.1 on 2020-10-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.BigIntegerField(blank='')),
                ('payed_on', models.DateTimeField(verbose_name='Payed On')),
                ('is_waived', models.BooleanField(default=False, verbose_name='Waiver')),
                ('payment_mode', models.CharField(choices=[('MPESA', 'M-PESA'), ('Bank', 'Bank')], max_length=50, verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Tax History',
                'verbose_name_plural': 'Tax History',
            },
        ),
    ]
