# Generated by Django 3.1.1 on 2020-10-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxationHistory',
            fields=[
                ('plot_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('payed_on', models.DateTimeField(verbose_name='Payed On')),
                ('is_waived', models.BooleanField(default=False, verbose_name='Waiver')),
                ('payment_mode', models.CharField(choices=[('MPESA', 'M-PESA'), ('Bank', 'Bank')], max_length=50, verbose_name='Payment Method')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount Payed')),
                ('balance', models.IntegerField(default=0, verbose_name='Arrears')),
                ('transaction_id', models.CharField(max_length=50, verbose_name='Transaction Id')),
            ],
            options={
                'verbose_name': 'Tax History',
                'verbose_name_plural': 'Tax History',
            },
        ),
    ]
