# Generated by Django 3.1.1 on 2020-10-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_taxationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxationhistory',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Arrear'),
        ),
    ]
