# Generated by Django 3.1.1 on 2020-10-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20201016_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxationhistory',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
    ]
