# Generated by Django 3.1.1 on 2020-10-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20201016_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxationhistory',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxationhistory',
            name='plot_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
