# Generated by Django 3.1.1 on 2020-10-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20201016_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxationhistory',
            name='id_number',
            field=models.IntegerField(default=10041314, verbose_name='Id Number'),
            preserve_default=False,
        ),
    ]
